# action.yml
name: "FHIR CLI Docker"
description: "Running Fhir helper CLI in docker action"
inputs:
  token:
    required: false
    description: "Credential to access to the repo to post the comment"
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
