# action.yml
name: "FHIR CLI Docker"
description: "Running Fhir helper CLI in docker action"
inputs:
  type:
    description: "The type command type"
    required: true
    default: "test"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.type }}
